### ISSUE TITLE
Energy function could be improved

### ISSUE THREAD

**Issue by mstamatakis** [mstamatakis/MesoscopicKineticApproximations#5]
```
     do j=1,nsites
      if(appr%hamilt%orig%term(i,j).ne.0) then
       s=s*state(appr%hamilt%orig%term(i,j))
      end if
     end do
```

Not advisable to use if statements inside do loops. Could degrade performance.

**Comment by evignola** [comment]
Then we should revise the data structure, because it contains zeros which could affect the correlation variable "s"; the if clause is there to prevent multiplication times zero.

**Comment by mstamatakis** [comment]
Issue resolved in general_reengineering branch.
